# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b30f5bc276fc5c299461cdbf1e6c41e551423cc203a9c82e907f61f2b912892ba200c1be965ac9a0cc306111f584903567af8354a876f38827cc79b20a781a78

test:
  secret_key_base: 22a50b6e4363ca937cdf3abdc82168243ac7f2a5e0a14bde9a7771af5cc8401719e4d81009bfe61aa449f7d04fd2b2700c2ff1d9f4a6336006db4f200d1c6fd0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
